@startuml
hide footbox
skinparam sequenceReferenceBackgroundColor #FFFFFF
actor User

participant ":Game" as Game
participant ":Storage" as Storage
participant ":Player" as Player
participant "{abstract} \n Equipment" as Equipment
loop until game is over
    User->Game : game.run()
    activate Game
    opt is Battle event
        Game->Game:saveGame()
        activate Game
        create Storage
        Game->Storage: new Storage()
        activate Storage
        Storage --> Game:
        deactivate Storage
        Game->Storage: .saveGame(...)
        activate Storage

        ref over Storage
            Write wave data into file
        end ref
        Storage -> Player: player.toText(): String
        activate Player
        loop equipments
        Player -> Equipment: equipment.toText(): String
        activate Equipment
        Equipment -> Player: Encoded equipment data
        deactivate Equipment
        end equipments
        Player --> Storage: Encoded player data
        deactivate Player
        ref over Storage
            Write player data into file
        end ref

        Storage --> Game
        destroy Storage
        Game --> Game
        deactivate Game
    end opt
end loop
@enduml

@startuml
hide footbox
skinparam sequenceReferenceBackgroundColor #FFFFFF

participant ":Storage" as Storage
participant ":FileWriter" as FileWriter
participant ":File" as File

activate Storage
group sd Write data into file
    Storage -> FileWriter: fw.write(data)
    activate FileWriter
    FileWriter -> File
    activate File
    File --> FileWriter
    deactivate File
    FileWriter --> Storage
    deactivate FileWriter
end group
@enduml
